Add files via upload
JoshuaSkelly/delver-example-mods pull request #47
Opened 2020-11-10 18:21 UTC by LordAmaury

Many untranslated strings added, many existing translation changes to consider.

2020-11-10 18:34 UTC, joshuaskelly requested changes
Can you make sure your JSON properties are quoted? Otherwise looking good! 👍

2020-11-10 18:34 UTC, joshuaskelly commented on language-pack-fr/data/messages/breach.dat
> +	messages: [
Please put quotes around JSON properties. Our JSON serializer can handle this, but it makes life easier and JSON linting possible.

E.g.
```json
{
    "messages": []
}
```

2020-11-10 18:34 UTC, joshuaskelly commented on language-pack-fr/data/messages/camp-note1.dat
> +	messages: [
Missing quotes.

2020-11-10 18:34 UTC, louiscarl approved these changes
Very welcome changes, thanks so much!

2020-11-10 19:56 UTC, LordAmaury commented
Files updated to include JSON quotes. Tell me if something is missing I checked all files one by one.

2020-11-11 00:45 UTC, joshuaskelly approved these changes
Thanks for making those changes!

2020-11-11 00:45 UTC, merged